### ISSUE TITLE
Typo in project description URL

### ISSUE THREAD

**Issue by hmitsch** [chaoss/metrics#12]
In the GitHub project description there is a link to the CHAOS metrics page by Linux Foundation. The link has a typo.

**As-Is:**
https://wiki.linuxfoundation.org/choss/metrics

**To-Be:**
https://wiki.linuxfoundation.org/chaoss/metrics

**Comment by hmitsch** [comment]
CC @GeorgLink

**Comment by hmitsch** [comment]
Is this the same as https://github.com/chaoss/metrics/pull/8 ?

**Comment by downeym** [comment]
I believe so, yes. :)

On Sep 24, 2017 16:56, "Henrik Mitsch" <notifications@github.com> wrote:

Is this the same as #8 <https://github.com/chaoss/metrics/pull/8> ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chaoss/metrics/issues/12#issuecomment-331748816>, or mute
the thread

**Comment by GeorgLink** [comment]
Thanks @hmitsch and @downeym  
Yes, that spelling mistake should have been fixed with #8. 
Let me know if you spot something else.
