### ISSUE TITLE
User Dependency should be in the Dependency section, not  here

### ISSUE THREAD

**Issue by LawrenceHecht** [chaoss/metrics#34]
User Dependency should be in the Dependency section, not  here

**Comment by LawrenceHecht** [comment]
oops, I was trying to say that User Dependency should not be in the Risk section

**Comment by GeorgLink** [comment]
At the Open Source Summit North America, we included User Dependency (Awareness) as a measure of Risk because a lack of awareness is a security risk also to your. Similar to how immunization only really works through community immunity which requires that most people get immunized.

Feel free to include it in your current pull request #35 anyways
