### ISSUE TITLE
Rename Second Level metrics folder

### ISSUE THREAD

**Issue by germonprez** [chaoss/metrics#5]
Rename metrics/metrics 
to
metrics/activitymetrics

Also, move the activity-metrics.md into that folder. Overall, I think we should reduce the noise on that front page.

**Comment by GeorgLink** [comment]
Good idea on renaming the folder.

I know the activity-metrics is not where we want to focus the discussion
right now. I had moved the template and schema into the folder.
I decided to keep the activity-metrics list because it points into the
folder and it would 'disappear' otherwise in the midst of all activity
metrics, making the folder useless.

**Comment by germonprez** [comment]
Sure. Makes sense on not losing the .md file. Maybe just renaming the metrics that we're interested in will help the issue.
